### ISSUE TITLE
Problem when return on suspend mode

### ISSUE THREAD

**Issue by uronito** [gw-wiscon/homebridge-winpc#1]
Hi,

When the computer returns from the suspended state , the computer turns off after the time of poll.

Excuse me for my poor english.

Regards

**Comment by gw-wiscon** [comment]
I removed the set command in the latest version, that should solve the problem.

**Comment by gw-wiscon** [comment]
Can you please reinstall the plugin?

**Comment by uronito** [comment]
In the last version 0.3.23 don't poll and don't check state.

Thanks

**Comment by gw-wiscon** [comment]
Unsure what it means, but I hope it works.

**Comment by uronito** [comment]
Now Insteon does not check the status of the notebook is on or off

**Comment by gw-wiscon** [comment]
???

**Comment by uronito** [comment]
insteon is a program for ios homekit.

In the last release the plugin dont poll if te state of the computer is on or off

the program turns on and off the computer well, but the plugin  dont check if the state of the computer is on or off.

Thanks

**Comment by gw-wiscon** [comment]
Can you sent me the winpc part your config.json file?

**Comment by gw-wiscon** [comment]
Hi Uronito, this problem should be solved by now.

**Comment by gw-wiscon** [comment]
Hi uronito, I am curious if if worked for you.

**Comment by gw-wiscon** [comment]
I also moved the callback to a moment before the actual request,
The actual request can block.

Sometime, I need to get it working when the network is gone.
Later this week, most likely.

**Comment by uronito** [comment]
Hi gw wiscon,

but had not seen the emails. now I test

Regards

2016-02-08 21:27 GMT+01:00 gw-wiscon notifications@github.com:

**Comment by gw-wiscon** [comment]
I believe my remark belongs in the onkyo thread - got confused somewhere.
Sorry.

**Comment by gw-wiscon** [comment]
But anyway, the winpc is the most stable off all.
Curious if you can get it working.

I had a real fight to have my windows 10 pc to react on WOL.
Microsoft actually stopped supporting it.

**Comment by uronito** [comment]
the plugin for pc works perfect!!!!!!

2016-02-08 22:28 GMT+01:00 Alberto Vercher Ibañez albert.vercher@gmail.com
:

**Comment by gw-wiscon** [comment]
I am happy you are set.
Closing the issue now.
Thanks!!

**Comment by uronito** [comment]
Thanks to you gw wiscon.

You ' re a crack

2016-02-09 19:00 GMT+01:00 gw-wiscon notifications@github.com:
