### ISSUE TITLE
Can't get it turn my PC on

### ISSUE THREAD

**Issue by chrislongden** [gw-wiscon/homebridge-winpc#2]
It's weird one but I was looking for a plugin that would be able to turn on/shutdown my computer.

I ended up installed "homebridge-wol" (https://github.com/alexgustafsson/homebridge-wol) which is just a wake on lan plugin but I set it up, tested and boom asking siri to turn my computer on, win!

So I looked around a bit more and found this plugin, so I used to the same software for shutting down (Airytec Switch Off) and set this plugin up - after removing "homebridge-wol".

For whatever the reason, this plugin just isn't turning my compurer on... I've checked the logs and it says it's sent the packets etc but my computer does nothing.

I even ended up comparing the code of both, this plugin and "homebridge-wol", which I found they use the same lib "wake-on-lan", so I'm at a lose end and would love this to work in full otherwise the only thing I can do at the moment is use 2 accessories, one using "homebridge-wol" for turning on and "homebridge-http" for turning off.

Any ideas why "homebridge-wol" would turn my pc on but this one won't?

**Comment by gw-wiscon** [comment]
Indeed, strange.
Can you send me the config used for both setups?

**Comment by chrislongden** [comment]
Basically just my mac and ip address, both plugins do the same thing with the same dependencies.

I've currently removed both and using the homebridge-http plugin where my raspberry pi is running a web server and ive created php pages to do the wol and ping.

Gonna give this a test and hopefully not find out that it's a random network issue, which I doubt but you never know.

If it doesn't work then I will install the plugins and send you the config each time.

**Comment by gw-wiscon** [comment]
I added an option to specify the ipAddress for the WOL request

can you try something like:

wol://40:39:51:04:99:c0?ip=10.0.1.23

Normally, it defaults to a broadcast address. But that is sometimes not enough.
That depends on the network structure.

**Comment by chrislongden** [comment]
I think it's just an issue with windows 8.1 (maybe other versions)... with the homebridge-wol, I manually shutdown my machine at the time of testing, then that worked turning it on, but it appears that the software (Airytec Switch Off) for doing the shutdown maybe the problem.

I've read that certain versions of windows (specially 8+) shutdown but kinda like a hibernate which leave the machine in a certain power state. I'm guessing that the Airytec Switch Off is telling windows to do a full shutdown and causing it to go into a different power state where WOL doesn't work.

My current setup, like I explained before using php pages, works but only if I change Airytec Switch Off from doing a System.Shutdown to System.Hibernate... so when I ask siri to shutdown the machine it gets left in the correct state for WOL... also clicking start and shutdown in windows gives the result.

**Comment by gw-wiscon** [comment]
Some where microsoft stopped to support WOL.
I had to update my network card driver to get it solved.

For each network card, there are some updates/configs required to get it to work.

**Comment by chrislongden** [comment]
Yeah think I'll settle with this hibernating way but I'm updating to
Windows 10 soon so see how much joy that will bring.

Maybe better to run a website locally and use .net page to use a power
shell command to do the shutdown at least I know it will shutdown how
Windows wants to.

**Comment by gw-wiscon** [comment]
Search the web for:
Windows 10 and wake on lan

It explains all the trouble.
And Windows 10 is not better in that area.
I have two windows 10 pc's, one where installing a specific driver worked and another where I cannot find the solution yet.

**Comment by chrislongden** [comment]
Does it work from hibernation?

**Comment by gw-wiscon** [comment]
Nope.

**Comment by gw-wiscon** [comment]
I believe, I can close this issue. if not m, then please re-open the issue.

**Comment by gw-wiscon** [comment]
Maybe this article is helpful:
https://www.raymond.cc/blog/how-to-remotely-turn-off-computer-from-lan-or-wan/

**Comment by chrislongden** [comment]
Yeah be seen that. I'm currently going to us the script function on that
software to use the shutdown command.

**Comment by gw-wiscon** [comment]
Or using nodejs:

https://github.com/typicode/stop-server
