### ISSUE TITLE
Dot not work anymore

### ISSUE THREAD

**Issue by RuneNyhuus** [gw-wiscon/homebridge-winpc#7]
This Plugin for homebridge dont work anymore.

Everytime getPowerState reports false, its making all homebridges accessories "non reponsive"
getPowerState - polling mode, return state:  false

**Comment by RuneNyhuus** [comment]
Compbability issue together with another plugin

**Comment by guillochon** [comment]
...which plugin? I'm getting the same outcome at the moment.
